package org.keywords;

import org.getpageobjects.GetPage;
import org.openqa.selenium.WebDriver;
import org.utils.RandomNumberGeneration;

public class Teacher_CreateClass extends GetPage{
	
	public static String className="";
	public static String classAccessCode;
	
	public Teacher_CreateClass(WebDriver driver) {
		super(driver);
	}
	
	public void clickOnRuddTitle() {
		click("Teacher_CreateClass","RuddTitle_css");
	}
	
	public void clickOnAddClassButton() throws Exception {
		Thread.sleep(7000);
		executeJavascript("$('#btnCreateClass')[0].click()");
		//click("Teacher_CreateClass","AddClass_css");
	}
	
	public String classTitleName() {
		className = "AutoGeneratedClass";
		int i = RandomNumberGeneration.generateRandomNumber();
		className = className+i;
		System.out.println(className);
		return className;
	}
	
	public void enterClassTitle() {
		type("Teacher_CreateClass","ClassName_id",classTitleName());
	}
	
	public void enterDescription() {
		type("Teacher_CreateClass","ClassDescription_id","This is Class generated by Automation Script");
	}
	
	public void checkAutoEnroll() {
		click("Teacher_CreateClass","AutoEnroll_id");
	}
	
	public void ClassAccessCode(){
		//scrollDownToElement("Teacher_CreateClass", "ClassAccessCode_id");
		classAccessCode = fetchText("Teacher_CreateClass", "ClassAccessCode_id");
		System.out.println(classAccessCode+"---------------->ClassAccessCode");
	}
	
	public void createClassButton() {
		click("Teacher_CreateClass","CreateClass_id");
	}
	
	public String createClassMessageDisplayed() {
		return fetchText("Teacher_CreateClass", "ClassCreatedAlertMessage_css");
	}
}
